SELECT DEV.*, 
NVL(PROD.SERVICE,'NA') AS SOURCE_SERVICE,
NVL(PROD.SITE,'NA') AS SOURCE_SITE, 
NVL(PROD.MONTH,TO_DATE('2001-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')) AS SOURCE_MONTH, 
PROD.PREMIER_REPORTING_PERIOD AS SOURCE_PREMIER_REPORTING_PERIOD,
NVL(PROD.METRIC_NAME_SUBMITTED,'NA') AS SOURCE_METRIC_NAME_SUBMITTED,
PROD.UPDATE_TIME AS SOURCE_UPDATE_TIME,
PROD.UPDATE_USER AS SOURCE_UPDATE_USER,
NVL(PROD.VALUE,-999) AS SOURCE_VALUE
FROM summary_repo_example_prod PROD
FULL JOIN summary_repo_example DEV
ON PROD.SERVICE = DEV.SERVICE AND
PROD.SITE = DEV.SITE AND
PROD.PREMIER_REPORTING_PERIOD = DEV.PREMIER_REPORTING_PERIOD AND
PROD.METRIC_NAME_SUBMITTED = DEV.METRIC_NAME_SUBMITTED;

MERGE INTO summary_repo_example  TARGET

USING (
SELECT DEV.*, 
NVL(PROD.SERVICE,'NA') AS SOURCE_SERVICE,
NVL(PROD.SITE,'NA') AS SOURCE_SITE, 
NVL(PROD.MONTH,TO_DATE('2001-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')) AS SOURCE_MONTH, 
PROD.PREMIER_REPORTING_PERIOD AS SOURCE_PREMIER_REPORTING_PERIOD,
NVL(PROD.METRIC_NAME_SUBMITTED,'NA') AS SOURCE_METRIC_NAME_SUBMITTED,
PROD.UPDATE_TIME AS SOURCE_UPDATE_TIME,
PROD.UPDATE_USER AS SOURCE_UPDATE_USER,
NVL(PROD.VALUE,-999) AS SOURCE_VALUE
FROM summary_repo_example_prod PROD
FULL JOIN summary_repo_example DEV
ON PROD.SERVICE = DEV.SERVICE AND
PROD.SITE = DEV.SITE AND
PROD.PREMIER_REPORTING_PERIOD = DEV.PREMIER_REPORTING_PERIOD AND
PROD.METRIC_NAME_SUBMITTED = DEV.METRIC_NAME_SUBMITTED
)

-- Specify fields to match on

ON (  TARGET."SITE" = SOURCE_SITE AND
      TARGET."SERVICE" = SOURCE_SERVICE AND
      TARGET."METRIC_NAME_SUBMITTED" = SOURCE_METRIC_NAME_SUBMITTED AND
      TARGET."PREMIER_REPORTING_PERIOD" = SOURCE_PREMIER_REPORTING_PERIOD)
-- Specify what fields to be updated when the records match

WHEN MATCHED THEN 
UPDATE  SET TARGET."VALUE" = SOURCE_VALUE,
            TARGET."UPDATE_TIME" = SOURCE_UPDATE_TIME,
            TARGET."UPDATE_USER" = SOURCE_UPDATE_USER
-- WHERE clause prevents the all the records from getting merged

WHERE TARGET."VALUE" <> SOURCE_VALUE

DELETE WHERE TARGET."VALUE" = -999

-- Specify fields to be joined on

WHEN NOT MATCHED THEN
INSERT( TARGET."SITE",
        TARGET."SERVICE",
        TARGET."METRIC_NAME_SUBMITTED",
        TARGET."VALUE", 
        TARGET."UPDATE_TIME", 
        TARGET."UPDATE_USER",
        TARGET."PREMIER_REPORTING_PERIOD",
        TARGET."MONTH") 
VALUES( SOURCE_SITE,
        SOURCE_SERVICE,
        SOURCE_METRIC_NAME_SUBMITTED,
        SOURCE_VALUE, 
        SOURCE_UPDATE_TIME,
        SOURCE_UPDATE_USER,
        SOURCE_PREMIER_REPORTING_PERIOD,
        SOURCE_MONTH);
